### ISSUE TITLE
pg8000.core.ProgrammingError: (u'ERROR', u'42601', u'syntax error at or near "$1"', u'15', u'scan.l', u'1053', u'scanner_yyerror', u'', u'')

### ISSUE THREAD

**Issue by d33tah** [mfenniak/pg8000#103]
```
Python 2.7.8 (default, Sep 24 2015, 18:26:19) 
[GCC 4.9.2 20150212 (Red Hat 4.9.2-6)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
[22:39:39]>>> import pg8000
[22:39:41]>>> c = pg8000.connect(database='postgres')
[22:39:44]>>> cur = c.cursor()
[22:39:51]>>> cur.execute('SET TIME ZONE %s', ('UTC', ))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/d/virtualenv/lib/python2.7/site-packages/pg8000/core.py", line 910, in execute
    self._c.execute(self, operation, args)
  File "/home/d/virtualenv/lib/python2.7/site-packages/pg8000/core.py", line 1969, in execute
    self.handle_messages(cursor)
  File "/home/d/virtualenv/lib/python2.7/site-packages/pg8000/core.py", line 2117, in handle_messages
    raise self.error
pg8000.core.ProgrammingError: (u'ERROR', u'42601', u'syntax error at or near "$1"', u'15', u'scan.l', u'1053', u'scanner_yyerror', u'', u'')
[22:40:17]>>> pg8000.paramstyle = "format"
[22:40:40]>>> cur.execute('SET TIME ZONE %s', ('UTC', ))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/d/virtualenv/lib/python2.7/site-packages/pg8000/core.py", line 910, in execute
    self._c.execute(self, operation, args)
  File "/home/d/virtualenv/lib/python2.7/site-packages/pg8000/core.py", line 1969, in execute
    self.handle_messages(cursor)
  File "/home/d/virtualenv/lib/python2.7/site-packages/pg8000/core.py", line 2117, in handle_messages
    raise self.error
pg8000.core.ProgrammingError: (u'ERROR', u'42601', u'syntax error at or near "$1"', u'15', u'scan.l', u'1053', u'scanner_yyerror', u'', u'')
```

**Comment by tlocke** [comment]
Here postgres is raising an error, and pg8000 is just reporting it. It seems that postgres doesn't let you parameterize SET statements. I think I recall coming across this before and having to create the full SQL string in the application.
