### ISSUE TITLE
Connecting via default unix socket without username/password

### ISSUE THREAD

**Issue by phdru** [mfenniak/pg8000#125]
Hello! I have the following settings in my pg_hba.conf:

```conf
local   all             all                                     peer
host    all             all             127.0.0.1/32            md5
```

That allows me to connect to any database via unix socket without authentication, but when I connect via `localhost` I am asked for password.

I.e., I can run

```shell
$ createdb test
$ psql test
connected
```

and be connected. Please note that by default `psql` (`libpq`, perhaps?) connects via unix socket; also note `psql` doesn't require username. If I want to connect via localhost I have to do it explicitly:

```shell
$ psql -h localhost test
Password:
```

I can also connect via non-standard unix socket, the option is also `-h host`:

```shell
$ psql -h /run/postgresql test
connected
```

Only directory is required. Driver `psycopg2` follows the conventions (perhaps because they are imposed by `libpq` and `psycopg2` uses `libpq`):

```python
con = psycopg2.connect(database="test")  # connected
```

```python
con = psycopg2.connect(database="test", host='/run/postgresql')  # connected
```

Unfortunately, pg8000 doesn't follow these conventions:

```python
con = pg8000.connect(database="test")

Traceback (most recent call last):
  File "./test_pg8000.py", line 7, in <module>
    con = pg8000.connect(database="test")
  File "/home/phd/.tox/SQLObject/py27-pg8000/local/lib/python2.7/site-packages/pg8000/__init__.py", line 105, in connect
    user, host, unix_sock, port, database, password, ssl, timeout)
  File "/home/phd/.tox/SQLObject/py27-pg8000/local/lib/python2.7/site-packages/pg8000/core.py", line 1231, in __init__
    "The 'user' connection parameter cannot be None")
pg8000.core.InterfaceError: The 'user' connection parameter cannot be None
```

```python
con = pg8000.connect(database="test", user='')

Traceback (most recent call last):
  File "./test_pg8000.py", line 8, in <module>
    con = pg8000.connect(database="test", user='')
  File "/home/phd/.tox/SQLObject/py27-pg8000/local/lib/python2.7/site-packages/pg8000/__init__.py", line 105, in connect
    user, host, unix_sock, port, database, password, ssl, timeout)
  File "/home/phd/.tox/SQLObject/py27-pg8000/local/lib/python2.7/site-packages/pg8000/core.py", line 1607, in __init__
    raise e
pg8000.core.InterfaceError: md5 password authentication failed
```

Seems like I'm connecting via localhost, not unix socket.

```python
con = pg8000.connect(database="test", user='',
                     unix_sock='/var/run/postgresql/.s.PGSQL.5432')

Traceback (most recent call last):
  File "./test_pg8000.py", line 10, in <module>
    unix_sock='/var/run/postgresql/.s.PGSQL.5432')
  File "/home/phd/.tox/SQLObject/py27-pg8000/local/lib/python2.7/site-packages/pg8000/__init__.py", line 105, in connect
    user, host, unix_sock, port, database, password, ssl, timeout)
  File "/home/phd/.tox/SQLObject/py27-pg8000/local/lib/python2.7/site-packages/pg8000/core.py", line 1607, in __init__
    raise e
pg8000.core.InterfaceError: md5 password authentication failed
```

Ouch! What is going on? What username must be passed?

Can pg8000 be fixed so that

```python
con = pg8000.connect(database="test")
```

connects via default unix socket, without username/password?

**Comment by phdru** [comment]
```python
con = pg8000.connect(database="test", user='phd',
                     unix_sock='/var/run/postgresql/.s.PGSQL.5432')  # connected
```

Ok, I see. User must be the current OS user.

**Comment by mfenniak** [comment]
Hey, sorry for the slow response, but the couple maintainers on this project aren't very active these days (myself included).  I see that you found that the ```user``` parameter does not default to the current OS user, as is common with other Postgres client libraries.  Sorry about that.
