### ISSUE TITLE
Overzealous parameter expansion

### ISSUE THREAD

**Issue by phdru** [mfenniak/pg8000#127]
Hi!
```python
cur = con.cursor()
cur.execute("CREATE TABLE test (id serial, test varchar)")
cur.execute("INSERT INTO test (test) VALUES ('%x')")

Traceback (most recent call last):
  File "./test1.py", line 11, in <module>
    cur.execute("INSERT INTO test (test) VALUES ('%x')")
  File "/home/phd/.tox/SQLObject/py27-pg8000/local/lib/python2.7/site-packages/pg8000/core.py", line 906, in execute
    self._c.execute(self, operation, args)
  File "/home/phd/.tox/SQLObject/py27-pg8000/local/lib/python2.7/site-packages/pg8000/core.py", line 1883, in execute
    statement, make_args = convert_paramstyle(paramstyle, operation)
  File "/home/phd/.tox/SQLObject/py27-pg8000/local/lib/python2.7/site-packages/pg8000/core.py", line 510, in convert_paramstyle
    "'%" + next_c + "' not supported in a quoted "
pg8000.core.InterfaceError: '%x' not supported in a quoted string within the query string
```

Sorry, I don't use parametrized query, I'm simply inserting a short 2-chars literal '%x'. The same code works with psycopg2.

**Comment by tlocke** [comment]
Yes, I think you're right. I've made a commit to ignore escapes within SQL literals https://github.com/mfenniak/pg8000/commit/6cca54bba27ef8bb801c2e041845c5be5a371b77.
