### ISSUE TITLE
Docker regression testing - py.error.EACCES: [Permission denied]

### ISSUE THREAD

**Issue by gregn610** [mfenniak/pg8000#145]
I couldn't get the docker regression testing to work on OSX using docker machine. 

    $ docker run -v `pwd`:/home/postgres/pg8000-src mfenniak/pg8000-test-env
    Traceback (most recent call last):
      File "/usr/local/bin/tox", line 9, in <module>
        load_entry_point('tox==2.5.0', 'console_scripts', 'tox')()
      File "/usr/local/lib/python2.7/dist-packages/tox/session.py", line 39, in main
        retcode = Session(config).runcommand()
      File "/usr/local/lib/python2.7/dist-packages/tox/session.py", line 337, in __init__
        config.logdir.ensure(dir=1)
      File "/usr/local/lib/python2.7/dist-packages/py/_path/local.py", line 524, in ensure
        return p._ensuredirs()
      File "/usr/local/lib/python2.7/dist-packages/py/_path/local.py", line 506, in _ensuredirs
        parent._ensuredirs()
      File "/usr/local/lib/python2.7/dist-packages/py/_path/local.py", line 509, in _ensuredirs
        self.mkdir()
      File "/usr/local/lib/python2.7/dist-packages/py/_path/local.py", line 459, in mkdir
        py.error.checked_call(os.mkdir, fspath(p))
      File "/usr/local/lib/python2.7/dist-packages/py/_error.py", line 85, in checked_call
        raise cls("%s%r" % (func.__name__, args))
    py.error.EACCES: [Permission denied]: mkdir('/home/postgres/pg8000-src/.tox',)

Which I unsuccessfully tried to work around with https://denibertovic.com/posts/handling-permissions-with-docker-volumes/#comment-3201673121 

Also, I think `./circleci/run-postgres-and-tox.sh` is missing from source control?

Big Thanks
/g

**Comment by tlocke** [comment]
Hi @gregn610, I've made a few changes in the testing recently to cope with the fact that we're moving to TravisCI from CircleCI, see https://github.com/mfenniak/pg8000/issues/166. As a result of this:

* TravisCI runs a matrix of Python and PostgreSQL versions.
* The local docker files and CircleCI files have been removed from the repo.
* `tox` now runs the tests against all the locally installed versions of Python and the installed version of PostgreSQL listening on port 5432.

Hope this helps :-)
