### ISSUE TITLE
How to insert data of type point

### ISSUE THREAD

**Issue by anupamme** [mfenniak/pg8000#156]
I have a table: _address_ whose last column is _geo_loc_ of type point.

To insert data in it in sql following sql command works:

INSERT INTO address VALUES (1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, point(2.5, 3.5));

When I try to run the same command using pg8000 I am not able to. This is what I am trying:

cursor.execute('INSERT INTO address (addressid, geo_loc) VALUES (%s, %s)', ( 5,'(1,2)' ))

but I get following error:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pg8000/core.py", line 1693, in execute
    ps = cache['ps'][key]
KeyError: ('INSERT INTO address (addressid, geo_loc) VALUES (%s, %s)', ((21, 1, <built-in method pack of Struct object at 0x1032f4500>), (705, 0, <function Connection.__init__.<locals>.text_out at 0x10330e8c8>)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pg8000/core.py", line 852, in execute
    self._c.execute(self, operation, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pg8000/core.py", line 1741, in execute
    self.handle_messages(cursor)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pg8000/core.py", line 1879, in handle_messages
    raise self.error
pg8000.core.ProgrammingError: ('ERROR', 'ERROR', '25P02', 'current transaction is aborted, commands ignored until end of transaction block', 'postgres.c', '1309', 'exec_parse_message')

**Comment by tlocke** [comment]
Hi @anupamme, yes pg8000 can handle the point type, but you need to enter it as a string, and then cast it to the `point` type. I've put an example at https://github.com/tlocke/pg8000#interactive-example. So it would be something like:

```
cursor.execute('INSERT INTO address (addressid, geo_loc) VALUES (%s, cast(%s as point))', ( 5,'(1,2)'))
```
