### ISSUE TITLE
Cannot execute ALTER USER WITH PASSWORD

### ISSUE THREAD

**Issue by ridha** [mfenniak/pg8000#160]
```
Python 3.6.4 (default, Dec 19 2017, 15:24:51)

>>>import pg8000
>>>conn = pg8000.connect(database='mydb')
>>>cursor = conn.cursor()
>>>cursor.execute("ALTER USER myuser WITH PASSWORD 'mypassword' ")
```
Exception:
```
ProgrammingError: ('ERROR', 'ERROR', '25P02', 'current transaction is aborted, commands ignored until end of transaction block', 'postgres.c', '1309', 'exec_parse_message')
```
Is there a way to make this work?
Any help would be much appreciated!

**Comment by sanandrea** [comment]
The same happens also with the following statement:

`cursor.execute("ALTER USER myuser WITH PASSWORD %s",('newpass'))`

Exception:
`Traceback (most recent call last):
  File "/Users/paloand/miniconda3/envs/graphex/lib/python3.6/site-packages/pg8000/core.py", line 1693, in execute
    ps = cache['ps'][key]
KeyError: ('ALTER USER myuser WITH PASSWORD %s', ((705, 0, <function Connection.__init__.<locals>.text_out at 0x10ab618c8>), (705, 0, <function Connection.__init__.<locals>.text_out at 0x10ab618c8>), (705, 0, <function Connection.__init__.<locals>.text_out at 0x10ab618c8>), (705, 0, <function Connection.__init__.<locals>.text_out at 0x10ab618c8>), (705, 0, <function Connection.__init__.<locals>.text_out at 0x10ab618c8>), (705, 0, <function Connection.__init__.<locals>.text_out at 0x10ab618c8>), (705, 0, <function Connection.__init__.<locals>.text_out at 0x10ab618c8>)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/paloand/miniconda3/envs/graphex/lib/python3.6/site-packages/pg8000/core.py", line 852, in execute
    self._c.execute(self, operation, args)
  File "/Users/paloand/miniconda3/envs/graphex/lib/python3.6/site-packages/pg8000/core.py", line 1741, in execute
    self.handle_messages(cursor)
  File "/Users/paloand/miniconda3/envs/graphex/lib/python3.6/site-packages/pg8000/core.py", line 1879, in handle_messages
    raise self.error
pg8000.core.ProgrammingError: ('ERROR', 'ERROR', '42601', 'syntax error at or near "$1"', '33', 'scan.l', '1087', 'scanner_yyerror')`

**Comment by Deniablesummer** [comment]
Is there any word on what that cause is? I get the same thing when attempting to change a users password and for attempting to drop a user.

`cursor.execute("DROP ROLE %s", [user])`

```
Traceback (most recent call last):
  File "C:\Users\asd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pg8000\core.py", line 1790, in execute
    ps = cache['ps'][key]
KeyError: ('DROP ROLE %s', ((705, 0, <function Connection.__init__.<locals>.text_out at 0x03C71540>),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\asd\Desktop\qwerty\Admin_Scripts\delete_user.py", line 67, in <module>
    main()
  File "C:\Users\asd\Desktop\qwerty\Admin_Scripts\delete_user.py", line 62, in main
    print(delete(sys.argv[3], sys.argv[6], conn, cursor))
  File "C:\Users\asd\Desktop\qwerty\Admin_Scripts\delete_user.py", line 46, in delete
    cursor.execute("DROP ROLE %s", [user])
  File "C:\Users\asd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pg8000\core.py", line 892, in execute
    self._c.execute(self, operation, args)
  File "C:\Users\asd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pg8000\core.py", line 1849, in execute
    self.handle_messages(cursor)
  File "C:\Users\asd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pg8000\core.py", line 1988, in handle_messages
    raise self.error
pg8000.core.ProgrammingError: ('ERROR', 'ERROR', '42601', 'syntax error at or near "$1"', '11', 'scan.l', '1087', 'scanner_yyerror')
```

Along with if I put the %s in brackets like in the interactive example it results in a different error. 

`cursor.execute("DROP ROLE (%s)", [user])`

```
Traceback (most recent call last):
  File "C:\Users\asd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pg8000\core.py", line 1790, in execute
    ps = cache['ps'][key]
KeyError: ('DROP ROLE (%s)', ((705, 0, <function Connection.__init__.<locals>.text_out at 0x03021540>),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\asd\Desktop\qwerty\Admin_Scripts\delete_user.py", line 67, in <module>
    main()
  File "C:\Users\asd\Desktop\qwerty\Admin_Scripts\delete_user.py", line 62, in main
    print(delete(sys.argv[3], sys.argv[6], conn, cursor))
  File "C:\Users\asd\Desktop\qwerty\Admin_Scripts\delete_user.py", line 46, in delete
    cursor.execute("DROP ROLE (%s)", [user])
  File "C:\Users\asd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pg8000\core.py", line 892, in execute
    self._c.execute(self, operation, args)
  File "C:\Users\asd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pg8000\core.py", line 1849, in execute
    self.handle_messages(cursor)
  File "C:\Users\asd\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pg8000\core.py", line 1988, in handle_messages
    raise self.error
pg8000.core.ProgrammingError: ('ERROR', 'ERROR', '42601', 'syntax error at or near "("', '11', 'scan.l', '1087', 'scanner_yyerror')
```

I found a workaround for now by using the following:
`cursor.execute("DROP ROLE " + user)`
But I am hoping to have the parameterized inputs working as I am not sure if the workaround is safe against SQL injection attacks.

**Comment by tlocke** [comment]
I think there are two separate problems here. The original question was why doesn't this work:

```
>>>import pg8000
>>>conn = pg8000.connect(database='mydb')
>>>cursor = conn.cursor()
>>>cursor.execute("ALTER USER myuser WITH PASSWORD 'mypassword' ")
```

and I think it's because some commands only work with `autocommit` on. See https://github.com/tlocke/pg8000#interactive-example for an example of turning autocommit on.

The other question is, why can't:
```
cursor.execute("DROP ROLE " + user)
```
be parameterized? As I understand it, only DML statements in PostgreSQL can be parameterized, not DDL statements.

**Comment by Deniablesummer** [comment]
@tlocke 
That's make a lot more sense on why I couldn't parameterize the `DROP ROLE` command. Thank you for clarification.

**Comment by ridha** [comment]
@tlocke Thank you for clarification and suggestion.
