### ISSUE TITLE
Support for authentication method of scram-sha-256

### ISSUE THREAD

**Issue by Deniablesummer** [mfenniak/pg8000#172]
Is there support for connecting to a postgresql server with an authentication and password encryption set to scram-sha-256? 

I'm getting the following error when attempting to connect since changing the server to scram-sha-256.
```
Traceback (most recent call last):
  File "C:\Users\asd\Desktop\asd\Database_Manipulation_Scripts\rebuild_file.py", line 798, in <module>
    main()
  File "C:\Users\asd\Desktop\asd\Database_Manipulation_Scripts\rebuild_file.py", line 746, in main
    port = int(sys.argv[2]), database=sys.argv[3], password=sys.argv[5])
  File "C:\Users\asd\AppData\Local\Programs\Python\Python37\lib\site-packages\pg8000\__init__.py", line 112, in connect
    application_name, max_prepared_statements)
  File "C:\Users\asd\AppData\Local\Programs\Python\Python37\lib\site-packages\pg8000\core.py", line 1467, in __init__
    self.message_types[code](self._read(data_len - 4), None)
  File "C:\Users\asd\AppData\Local\Programs\Python\Python37\lib\site-packages\pg8000\core.py", line 1683, in handle_AUTHENTICATION_REQUEST
    " not recognized by pg8000.")
pg8000.core.InterfaceError: Authentication method 10 not recognized by pg8000.
```

Edit:
So I went through the source and found that it is not supported. Auth code 10 isn't actually even listed in different authentication codes for `handle_AUTHENTICATION_REQUEST()` at this time.

I instead, would like to ask if it could be implemented.  :) I took a look to see if I'd be able to fork, implement and make a pull request for it myself, but it looks like I'd be way in above my head for something like that.

**Comment by tlocke** [comment]
Please see https://github.com/tlocke/pg8000/issues/4
